
create table Country(
countryid serial,
country varchar(50),
zone varchar(10)
 );
 
Insert into Country(countryid,country,zone) values('1','Antigua & Bar.','60W00');
Insert into Country(countryid,country,zone) values('2','Afghanistan','67E30');
Insert into Country(countryid,country,zone) values('3','Albania','15E00');
Insert into Country(countryid,country,zone) values('4','Algeria','15E00');
Insert into Country(countryid,country,zone) values('5','Andorra','15E00');
Insert into Country(countryid,country,zone) values('6','Angola','15E00');
Insert into Country(countryid,country,zone) values('7','Anguilla','60W00');
Insert into Country(countryid,country,zone) values('8','Argentina','45W00');
Insert into Country(countryid,country,zone) values('9','Armenia','45E00');
Insert into Country(countryid,country,zone) values('10','Aruba','60W00');
Insert into Country(countryid,country,zone) values('11','Austria','15E00');
Insert into Country(countryid,country,zone) values('12','Australia','150E00');
Insert into Country(countryid,country,zone) values('13','Azerbaijan','45E00');
Insert into Country(countryid,country,zone) values('14','Azores','30W00');
Insert into Country(countryid,country,zone) values('15','Burkina & Fasso','0W00');
Insert into Country(countryid,country,zone) values('16','Bosnia & Herz.','15E00');
Insert into Country(countryid,country,zone) values('17','Bahamas','75W00');
Insert into Country(countryid,country,zone) values('18','Bahrain','60E00');
Insert into Country(countryid,country,zone) values('19','Bangladesh','90E00');
Insert into Country(countryid,country,zone) values('20','Barbados','60W00');
Insert into Country(countryid,country,zone) values('21','Belarus','30E00');
Insert into Country(countryid,country,zone) values('22','Belgium','15E00');
Insert into Country(countryid,country,zone) values('23','Belize','90W00');
Insert into Country(countryid,country,zone) values('24','Benin','15E00');
Insert into Country(countryid,country,zone) values('25','Bermuda','60W00');
Insert into Country(countryid,country,zone) values('26','Bhutan','82E30');
Insert into Country(countryid,country,zone) values('27','Bolivia','60W00');
Insert into Country(countryid,country,zone) values('28','Botswana','30E00');
Insert into Country(countryid,country,zone) values('29','Brazil','45W00');
Insert into Country(countryid,country,zone) values('30','Brunei','120E00');
Insert into Country(countryid,country,zone) values('31','Bulgaria','30E00');
Insert into Country(countryid,country,zone) values('32','Burma','97E30');
Insert into Country(countryid,country,zone) values('33','Burundi','30E00');
Insert into Country(countryid,country,zone) values('34','Cen. Afr. Rep.','15E00');
Insert into Country(countryid,country,zone) values('36','Cape Verde','15W00');
Insert into Country(countryid,country,zone) values('37','Cambodia','105E00');
Insert into Country(countryid,country,zone) values('38','Cameroon','15E00');
Insert into Country(countryid,country,zone) values('39','Canada','75W00');
Insert into Country(countryid,country,zone) values('40','Ceuta','0W00');
Insert into Country(countryid,country,zone) values('41','Chad','15E00');
Insert into Country(countryid,country,zone) values('42','Channel Is.','60W00');
Insert into Country(countryid,country,zone) values('43','Chile','60W00');
Insert into Country(countryid,country,zone) values('44','China','120E00');
Insert into Country(countryid,country,zone) values('45','Canary Is.','75W00');
Insert into Country(countryid,country,zone) values('46','Colombia','75W00');
Insert into Country(countryid,country,zone) values('47','Comoros','45E00');
Insert into Country(countryid,country,zone) values('48','Congo','15E00');
Insert into Country(countryid,country,zone) values('49','Cook Is.','150W00');
Insert into Country(countryid,country,zone) values('50','Costa Rica','90W00');
Insert into Country(countryid,country,zone) values('51','Croatia','15E00');
Insert into Country(countryid,country,zone) values('52','Cuba','75W00');
Insert into Country(countryid,country,zone) values('53','Cayman Is.','75W00');
Insert into Country(countryid,country,zone) values('54','Cyprus','30E00');
Insert into Country(countryid,country,zone) values('55','Czecho','15E00');
Insert into Country(countryid,country,zone) values('56','Dominican Rep.','60W00');
Insert into Country(countryid,country,zone) values('57','Denmark','15E00');
Insert into Country(countryid,country,zone) values('58','Djibouti','45E00');
Insert into Country(countryid,country,zone) values('59','Dominica','60W00');
Insert into Country(countryid,country,zone) values('60','Eq. Guinea','15E00');
Insert into Country(countryid,country,zone) values('61','Ecuador','75W00');
Insert into Country(countryid,country,zone) values('62','Egypt','30E00');
Insert into Country(countryid,country,zone) values('63','El Salvador','90W00');
Insert into Country(countryid,country,zone) values('64','Estonia','30E00');
Insert into Country(countryid,country,zone) values('65','Ethiopia','45E00');
Insert into Country(countryid,country,zone) values('66','Faeroe Is.','0W00');
Insert into Country(countryid,country,zone) values('67','Fed.St.of Micro.','150E00');
Insert into Country(countryid,country,zone) values('68','Falkland Is.','0W00');
Insert into Country(countryid,country,zone) values('69','Fiji','180E00');
Insert into Country(countryid,country,zone) values('70','Finland','30E00');
Insert into Country(countryid,country,zone) values('71','France','15E00');
Insert into Country(countryid,country,zone) values('72','Guinea-Bissau','0W00');
Insert into Country(countryid,country,zone) values('73','Greenland','45W00');
Insert into Country(countryid,country,zone) values('74','Gabon','15E00');
Insert into Country(countryid,country,zone) values('75','Gambia','0W00');
Insert into Country(countryid,country,zone) values('76','Georgia','45E00');
Insert into Country(countryid,country,zone) values('77','Germany','15E00');
Insert into Country(countryid,country,zone) values('78','Ghana','0W00');
Insert into Country(countryid,country,zone) values('79','Gibraltar','15E00');
Insert into Country(countryid,country,zone) values('80','Guiana','60W00');
Insert into Country(countryid,country,zone) values('81','Greece','30E00');
Insert into Country(countryid,country,zone) values('82','Grenada','60W00');
Insert into Country(countryid,country,zone) values('83','Guadeloupe','60W00');
Insert into Country(countryid,country,zone) values('84','Guam','150E00');
Insert into Country(countryid,country,zone) values('85','Guatemala','90W00');
Insert into Country(countryid,country,zone) values('86','Guinea','0W00');
Insert into Country(countryid,country,zone) values('87','Guyana','45W00');
Insert into Country(countryid,country,zone) values('88','Hong Kong','120E00');
Insert into Country(countryid,country,zone) values('89','Haiti','75W00');
Insert into Country(countryid,country,zone) values('90','Honduras','90W00');
Insert into Country(countryid,country,zone) values('91','Hungary','15E00');
Insert into Country(countryid,country,zone) values('92','Ivory Coast','0W00');
Insert into Country(countryid,country,zone) values('93','Isle of Man','0W00');
Insert into Country(countryid,country,zone) values('94','India','82E30');
Insert into Country(countryid,country,zone) values('95','Iceland','0W00');
Insert into Country(countryid,country,zone) values('96','Indonesia','105E00');
Insert into Country(countryid,country,zone) values('97','Iran','52E30');
Insert into Country(countryid,country,zone) values('98','Iraq','45E00');
Insert into Country(countryid,country,zone) values('99','Ireland','0W00');
Insert into Country(countryid,country,zone) values('100','Israel','30E00');
Insert into Country(countryid,country,zone) values('101','Italy','15E00');
Insert into Country(countryid,country,zone) values('102','Jamaica','75W00');
Insert into Country(countryid,country,zone) values('103','Japan','135E00');
Insert into Country(countryid,country,zone) values('104','Jordan','30E00');
Insert into Country(countryid,country,zone) values('105','Kazakhstan','75E00');
Insert into Country(countryid,country,zone) values('106','Kenya','45E00');
Insert into Country(countryid,country,zone) values('107','Kiribati','180E00');
Insert into Country(countryid,country,zone) values('108','Kuwait','45E00');
Insert into Country(countryid,country,zone) values('109','Kyrgyzstan','75E00');
Insert into Country(countryid,country,zone) values('110','Laos','105E00');
Insert into Country(countryid,country,zone) values('111','Latvia','30E00');
Insert into Country(countryid,country,zone) values('112','Libya','15E00');
Insert into Country(countryid,country,zone) values('113','Lebanon','30E00');
Insert into Country(countryid,country,zone) values('114','Lesotho','30E00');
Insert into Country(countryid,country,zone) values('115','Liberia','0W00');
Insert into Country(countryid,country,zone) values('116','Liechtenstein','15E00');
Insert into Country(countryid,country,zone) values('117','Lithuania','30E00');
Insert into Country(countryid,country,zone) values('118','Luxembourg','15E00');
Insert into Country(countryid,country,zone) values('119','Macao','120E00');
Insert into Country(countryid,country,zone) values('120','Macedonia','15E00');
Insert into Country(countryid,country,zone) values('121','Madagascar','45E00');
Insert into Country(countryid,country,zone) values('122','Madeira','15W00');
Insert into Country(countryid,country,zone) values('123','Malaysia','120E00');
Insert into Country(countryid,country,zone) values('124','Maldives','75E00');
Insert into Country(countryid,country,zone) values('125','Mali','0W00');
Insert into Country(countryid,country,zone) values('126','Malta','15E00');
Insert into Country(countryid,country,zone) values('127','Marshall Is.','165E00');
Insert into Country(countryid,country,zone) values('128','Martinique','60W00');
Insert into Country(countryid,country,zone) values('129','Mauritania','0W00');
Insert into Country(countryid,country,zone) values('130','Mauritius','60E00');
Insert into Country(countryid,country,zone) values('131','Mayotte','45E00');
Insert into Country(countryid,country,zone) values('132','Melila','0W00');
Insert into Country(countryid,country,zone) values('133','Mexico','90W00');
Insert into Country(countryid,country,zone) values('134','Moldova','30E00');
Insert into Country(countryid,country,zone) values('135','Monaco','15E00');
Insert into Country(countryid,country,zone) values('136','Montserrat','60W00');
Insert into Country(countryid,country,zone) values('137','Mongolia','120E00');
Insert into Country(countryid,country,zone) values('138','Morocco','15E00');
Insert into Country(countryid,country,zone) values('139','Mozambique','30E00');
Insert into Country(countryid,country,zone) values('140','Malwi','30E00');
Insert into Country(countryid,country,zone) values('141','Myanmar','90E00');
Insert into Country(countryid,country,zone) values('142','North Korea','120E00');
Insert into Country(countryid,country,zone) values('143','North MarianasCh','150E00');
Insert into Country(countryid,country,zone) values('144','New Zealand','180E00');
Insert into Country(countryid,country,zone) values('145','Namibia','30E00');
Insert into Country(countryid,country,zone) values('146','Nauru','180E00');
Insert into Country(countryid,country,zone) values('147','Nepal','82E30');
Insert into Country(countryid,country,zone) values('148','Netherlands Ant.','60W00');
Insert into Country(countryid,country,zone) values('149','Netherlands','15E00');
Insert into Country(countryid,country,zone) values('150','New Caledonia','165E00');
Insert into Country(countryid,country,zone) values('151','Nicaragua','90W00');
Insert into Country(countryid,country,zone) values('152','Niger','15E00');
Insert into Country(countryid,country,zone) values('153','Nigeria','15E00');
Insert into Country(countryid,country,zone) values('154','Niue','165W00');
Insert into Country(countryid,country,zone) values('155','Norway','15E00');
Insert into Country(countryid,country,zone) values('156','Oman','60E00');
Insert into Country(countryid,country,zone) values('157','Pitcairn Is.','127W30');
Insert into Country(countryid,country,zone) values('158','Pakistan','82E30');
Insert into Country(countryid,country,zone) values('159','Panama','75W00');
Insert into Country(countryid,country,zone) values('160','Papua New Guinea','150E00');
Insert into Country(countryid,country,zone) values('161','Paraguay','60W00');
Insert into Country(countryid,country,zone) values('162','Peru','75W00');
Insert into Country(countryid,country,zone) values('163','Philippines','120E00');
Insert into Country(countryid,country,zone) values('164','Poland','15E00');
Insert into Country(countryid,country,zone) values('165','Polynesia','150W00');
Insert into Country(countryid,country,zone) values('166','Portugal','0W00');
Insert into Country(countryid,country,zone) values('167','Puerto Rico','60W00');
Insert into Country(countryid,country,zone) values('168','Qatar','45E00');
Insert into Country(countryid,country,zone) values('169','Reunion','60E00');
Insert into Country(countryid,country,zone) values('170','Romania','30E00');
Insert into Country(countryid,country,zone) values('171','Rep. of Palau','135E00');
Insert into Country(countryid,country,zone) values('172','Russia','30E00');
Insert into Country(countryid,country,zone) values('173','Rwanda','30E00');
Insert into Country(countryid,country,zone) values('174','Saint Lucia','60W00');
Insert into Country(countryid,country,zone) values('175','San Marino','15E00');
Insert into Country(countryid,country,zone) values('176','South Africa','30E00');
Insert into Country(countryid,country,zone) values('177','Saudi Arabia','45E00');
Insert into Country(countryid,country,zone) values('178','South Korea','135E00');
Insert into Country(countryid,country,zone) values('179','Sri Lanka','82E30');
Insert into Country(countryid,country,zone) values('180','Samoa','165W00');
Insert into Country(countryid,country,zone) values('181','Sao Tome & E-Pri','0W00');
Insert into Country(countryid,country,zone) values('182','Senegal','0W00');
Insert into Country(countryid,country,zone) values('183','Seychelles','60E00');
Insert into Country(countryid,country,zone) values('184','Sierra Leone','0W00');
Insert into Country(countryid,country,zone) values('185','Singapore','120E00');
Insert into Country(countryid,country,zone) values('186','Slovenia','15E00');
Insert into Country(countryid,country,zone) values('187','Slovak','15E00');
Insert into Country(countryid,country,zone) values('188','Solomon Is.','165E00');
Insert into Country(countryid,country,zone) values('189','Somalia','45E00');
Insert into Country(countryid,country,zone) values('190','Spain','15E00');
Insert into Country(countryid,country,zone) values('191','St. Helena','0W00');
Insert into Country(countryid,country,zone) values('192','St. Kitts-Nevis','60W00');
Insert into Country(countryid,country,zone) values('193','St. Pierre & Miq','45W00');
Insert into Country(countryid,country,zone) values('194','St. Vin. & Gren.','60W00');
Insert into Country(countryid,country,zone) values('195','Sudan','30E00');
Insert into Country(countryid,country,zone) values('196','Suriname','45W00');
Insert into Country(countryid,country,zone) values('197','Swaziland','30E00');
Insert into Country(countryid,country,zone) values('198','Sweden','15E00');
Insert into Country(countryid,country,zone) values('199','Switzerland','15E00');
Insert into Country(countryid,country,zone) values('200','Syria','30E00');
Insert into Country(countryid,country,zone) values('201','Turks &Caicos','75W00');
Insert into Country(countryid,country,zone) values('202','Trinidad &Tobago','60W00');
Insert into Country(countryid,country,zone) values('203','Taiwan','120E00');
Insert into Country(countryid,country,zone) values('204','Tajikistan','60E00');
Insert into Country(countryid,country,zone) values('205','Tanzania','45E00');
Insert into Country(countryid,country,zone) values('206','Thailand','105E00');
Insert into Country(countryid,country,zone) values('207','Togo','0E00');
Insert into Country(countryid,country,zone) values('208','Tonga','195W00');
Insert into Country(countryid,country,zone) values('209','Tunisia','15E00');
Insert into Country(countryid,country,zone) values('210','Turkey','45E00');
Insert into Country(countryid,country,zone) values('211','Turkmenistan','60E00');
Insert into Country(countryid,country,zone) values('212','Tuvalu','180E00');
Insert into Country(countryid,country,zone) values('213','U.K.','0W00');
Insert into Country(countryid,country,zone) values('214','U.A.E.','60E00');
Insert into Country(countryid,country,zone) values('215','Uganda','45E00');
Insert into Country(countryid,country,zone) values('216','Ukraine','30E00');
Insert into Country(countryid,country,zone) values('217','Uruguay','45W00');
Insert into Country(countryid,country,zone) values('218','U.S.A.','75W00');
Insert into Country(countryid,country,zone) values('219','Uzbekistan','75E00');
Insert into Country(countryid,country,zone) values('220','Virgin Is. (UK)','60W00');
Insert into Country(countryid,country,zone) values('221','Virgin Is. (USA)','60W00');
Insert into Country(countryid,country,zone) values('222','Vatican City','15E00');
Insert into Country(countryid,country,zone) values('223','Vanuatu','165E00');
Insert into Country(countryid,country,zone) values('224','Venezuella','60W00');
Insert into Country(countryid,country,zone) values('225','Vietnam','105E00');
Insert into Country(countryid,country,zone) values('226','Wallis & Futuna','180E00');
Insert into Country(countryid,country,zone) values('227','West Sahara','15W00');
Insert into Country(countryid,country,zone) values('228','WestSamoa','165W00');
Insert into Country(countryid,country,zone) values('229','Yemen North','45E00');
Insert into Country(countryid,country,zone) values('230','Yugoslavia','15E00');
Insert into Country(countryid,country,zone) values('231','Zambia','30E00');
Insert into Country(countryid,country,zone) values('232','Zimbabwe','30E00');
Insert into Country(countryid,country,zone) values('233','Zaire','30E00');
